// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfgNAC8_vF3LrezS72ykEAtPS1BrNPAE',
    appId: '1:329805692344:web:96771e44fb4773daf4a34d',
    messagingSenderId: '329805692344',
    projectId: 'mfucycleapp',
    authDomain: 'mfucycleapp.firebaseapp.com',
    storageBucket: 'mfucycleapp.appspot.com',
    measurementId: 'G-6NTNWQ3KF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcCERO_fiMSvmZWWubes7JWIXi7uXhlY',
    appId: '1:329805692344:android:ec5d694ae3f7772ef4a34d',
    messagingSenderId: '329805692344',
    projectId: 'mfucycleapp',
    storageBucket: 'mfucycleapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzm9J-r75A5VIE8AcrALiu20Q2mUdwrlo',
    appId: '1:329805692344:ios:538aa25a9ffab8d6f4a34d',
    messagingSenderId: '329805692344',
    projectId: 'mfucycleapp',
    storageBucket: 'mfucycleapp.appspot.com',
    iosClientId: '329805692344-j9h7eb1ipgub3tgjk91lu08fhtdjugfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleBikeMfu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzm9J-r75A5VIE8AcrALiu20Q2mUdwrlo',
    appId: '1:329805692344:ios:538aa25a9ffab8d6f4a34d',
    messagingSenderId: '329805692344',
    projectId: 'mfucycleapp',
    storageBucket: 'mfucycleapp.appspot.com',
    iosClientId: '329805692344-j9h7eb1ipgub3tgjk91lu08fhtdjugfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleBikeMfu',
  );
}
