// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxW-4MgRUnadEYLSljtUAHpPWjmloKK04',
    appId: '1:391016537147:web:3c7e79c96bf6aca75b101e',
    messagingSenderId: '391016537147',
    projectId: 'mfucycleapp2',
    authDomain: 'mfucycleapp2.firebaseapp.com',
    storageBucket: 'mfucycleapp2.appspot.com',
    measurementId: 'G-7RJ48ZTBGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HlRzr4S7vylsatX4Z0j8OBKAEz4wQ94',
    appId: '1:391016537147:android:5f38dc494a8f372c5b101e',
    messagingSenderId: '391016537147',
    projectId: 'mfucycleapp2',
    storageBucket: 'mfucycleapp2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW48w9BoSIDbKMrSb-L8cfybHLQw-_yWk',
    appId: '1:391016537147:ios:b3ac59accbc3ea5e5b101e',
    messagingSenderId: '391016537147',
    projectId: 'mfucycleapp2',
    storageBucket: 'mfucycleapp2.appspot.com',
    iosClientId: '391016537147-4c9sj5frvbjq2fe51dcmu331egm97ln1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleBikeMfu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW48w9BoSIDbKMrSb-L8cfybHLQw-_yWk',
    appId: '1:391016537147:ios:b3ac59accbc3ea5e5b101e',
    messagingSenderId: '391016537147',
    projectId: 'mfucycleapp2',
    storageBucket: 'mfucycleapp2.appspot.com',
    iosClientId: '391016537147-4c9sj5frvbjq2fe51dcmu331egm97ln1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cycleBikeMfu',
  );
}
